"""Summarise coverage and extraction quality.

Writes ``data/quality_by_year.csv`` (one line per publication and year) and
``docs/COVERAGE.md`` (the same as readable tables, plus download failures).

Usage:
    uv run python -m ncrb.report
"""

from __future__ import annotations

import csv
from collections import defaultdict

from .crawl import CATALOG, ROOT
from .download import FILES
from .extract import FILE_INDEX, INDEX

OUT_CSV = ROOT / "data" / "quality_by_year.csv"
OUT_MD = ROOT / "docs" / "COVERAGE.md"
PUBS = {"cii": "Crime in India", "adsi": "Accidental Deaths & Suicides in India", "psi": "Prison Statistics India"}


def read(path):
    return list(csv.DictReader(path.open(encoding="utf-8"))) if path.exists() else []


def main() -> None:
    catalog, files, file_idx, tables = read(CATALOG), read(FILES), read(FILE_INDEX), read(INDEX)
    stats: dict[tuple[str, int], dict] = defaultdict(lambda: defaultdict(int))
    urls = defaultdict(set)
    for r in catalog:
        urls[(r["publication"], int(r["year"]))].add(r["url"])
    for k, u in urls.items():
        stats[k]["files_listed"] = len(u)
    for r in files:
        k = (r["publication"], int(r["year"]))
        stats[k]["files_downloaded"] += r["status"] == "ok"
        stats[k]["files_missing"] += r["status"] != "ok"
    for r in file_idx:
        k = (r["publication"], int(r["year"]))
        stats[k]["pages"] += int(r["pages"] or 0)
        stats[k]["pages_ocr"] += int(r["pages_ocr"] or 0)
        stats[k]["files_with_tables"] += int(r["tables"] or 0) > 0
    for r in tables:
        k = (r["publication"], int(r["year"]))
        s = stats[k]
        s["tables"] += 1
        s["cells"] += int(r["n_cells"] or 0)
        s["tables_" + r["method"]] += 1
        s["checks_total"] += int(r["checks_total"] or 0)
        s["checks_passed"] += int(r["checks_passed"] or 0)
        tier = "ocr" if r["method"] in ("pdf_ocr", "pdf_mixed", "pdf_vlm") else "text"
        s[f"checks_total_{tier}"] += int(r["checks_total"] or 0)
        s[f"checks_passed_{tier}"] += int(r["checks_passed"] or 0)
        if int(r["checks_total"] or 0):
            s["tables_checked"] += 1
            s["tables_all_pass"] += r["checks_total"] == r["checks_passed"]

    fields = [
        "publication", "year", "files_listed", "files_downloaded", "files_missing", "files_with_tables", "pages", "pages_ocr",
        "tables", "tables_pdf_text", "tables_excel", "tables_pdf_ocr", "tables_pdf_mixed", "tables_pdf_vlm", "cells",
        "checks_total", "checks_passed", "check_pass_rate", "tables_checked", "tables_all_pass",
        "checks_total_text", "checks_passed_text", "checks_total_ocr", "checks_passed_ocr",
    ]
    rows = []
    for (pub, year), s in sorted(stats.items()):
        rate = f"{s['checks_passed'] / s['checks_total']:.4f}" if s["checks_total"] else ""
        rows.append({"publication": pub, "year": year, **{f: s.get(f, 0) for f in fields[2:]}, "check_pass_rate": rate})
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)

    md = ["# Coverage and extraction quality", "", "Generated by `uv run python -m ncrb.report`; do not edit by hand.", ""]
    md += [
        "`checks` counts the cells of printed TOTAL rows that could be compared with the sum of the rows above them;",
        "`pass` is the share that matched. OCR = tables read from scanned pages. See [DATA_NOTES.md](DATA_NOTES.md).",
        "",
    ]
    for pub, name in PUBS.items():
        sel = [r for r in rows if r["publication"] == pub]
        if not sel:
            continue
        tot = lambda f: sum(int(r[f]) for r in sel)  # noqa: E731
        md += [f"## {name} (`{pub}`)", ""]
        pct = lambda a, b: f"{a / b:.1%}" if b else "–"  # noqa: E731
        md += [
            f"{tot('files_downloaded'):,} files downloaded ({tot('files_missing')} listed but unavailable), "
            f"{tot('tables'):,} tables, {tot('cells'):,} cells.",
            "",
            f"- Text-layer PDFs and Excel: {tot('checks_passed_text'):,} of {tot('checks_total_text'):,} checked total cells match "
            f"({pct(tot('checks_passed_text'), tot('checks_total_text'))}).",
            f"- OCR of scanned pages: {tot('checks_passed_ocr'):,} of {tot('checks_total_ocr'):,} "
            f"({pct(tot('checks_passed_ocr'), tot('checks_total_ocr'))}).",
            "",
            "| Year | Files | Tables | Text | Excel | OCR | Cells | Checks (text) | Pass | Checks (OCR) | Pass |",
            "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
        for r in sel:
            ocr = int(r["tables_pdf_ocr"]) + int(r["tables_pdf_mixed"]) + int(r["tables_pdf_vlm"])
            ct, pt_, co, po = (int(r[k]) for k in ("checks_total_text", "checks_passed_text", "checks_total_ocr", "checks_passed_ocr"))
            md.append(
                f"| {r['year']} | {r['files_downloaded']} | {r['tables']} | {r['tables_pdf_text']} | {r['tables_excel']} | {ocr} | "
                f"{int(r['cells']):,} | {ct:,} | {pct(pt_, ct)} | {co:,} | {pct(po, co)} |"
            )
        md.append("")
    bad = [r for r in files if r["status"] != "ok"]
    md += ["## Files listed on ncrb.gov.in that could not be downloaded", ""]
    if bad:
        md += ["| Publication | Year | Status | URL |", "|---|---|---|---|"]
        md += [f"| {r['publication']} | {r['year']} | {r['status']} {r['error']} | {r['url']} |" for r in sorted(bad, key=lambda r: (r["publication"], r["year"]))]
    else:
        md.append("None.")
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(md) + "\n", encoding="utf-8")
    print(f"wrote {OUT_CSV.relative_to(ROOT)} and {OUT_MD.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
